name: Build Artifacts

on: [ push, pull_request ]

jobs:
  build:
    strategy:
      matrix:
        arch: [armhf,arm64]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          submodules: recursive
      - name: Install Dependencies
        run: |
          python3 -m pip install clickable-ut
      - name: Build
        run: |
          clickable build --arch ${{ matrix.arch }}
      - name: Upload Artifacts
        uses: actions/upload-artifact@v3
        with:
          name: KalTracker_${{ matrix.arch }}
          path: build/*/app/*.click
          if-no-files-found: error
          retention-days: 20
